---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogpub
  labels:
    app: blogpub
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: blogpub
  template:
    metadata:
      labels:
        app: blogpub
    spec:
      volumes:
        - name: keys-volume
          secret:
            secretName: blogpub-keys
            defaultMode: 0444
      containers:
        - name: blogpub
          image: localhost:32000/blogpub:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: keys-volume
              readOnly: true
              mountPath: "/app/lib/blogpub-0.1.0/priv/keys"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: blogpub-secret
                  key: DATABASE_URL

            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: blogpub-secret
                  key: SECRET_KEY_BASE

            - name: BLOGPUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: blogpub-secret
                  key: BLOGPUB_API_KEY

            - name: PHX_HOST
              value: pub.ulfurinn.net

            - name: BLOGPUB_DOMAIN
              value: ulfurinn.net

            - name: BLOGPUB_WEBSITE
              value: https://ulfurinn.net/

            - name: BLOGPUB_NAME
              value: Valeri Sokolov

            - name: BLOGPUB_GRAVATAR_EMAIL
              value: ulfurinn@ulfurinn.net

            - name: BLOGPUB_FEEDS
              value: blog,links,notes

            - name: BLOGPUB_BLOG_FEED_URL
              value: https://ulfurinn.net/blog/index.xml

            - name: BLOGPUB_BLOG_DESCRIPTION
              value: ActivityPub mirror for the blog feed

            - name: BLOGPUB_LINKS_FEED_URL
              value: https://ulfurinn.net/links/index.xml

            - name: BLOGPUB_LINKS_DESCRIPTION
              value: ActivityPub mirror for the link feed

            - name: BLOGPUB_NOTES_FEED_URL
              value: https://ulfurinn.net/notes/index.xml

            - name: BLOGPUB_NOTES_DESCRIPTION
              value: ActivityPub mirror for the note feed

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: blogpub
  labels:
    app: blogpub
spec:
  ports:
    - port: 80
      targetPort: 4000
  selector:
    app: blogpub
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogpub
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   more_clear_input_headers "X-Forwarded-Host";
    #   proxy_set_header X-Forwarded-Host $http_x_forwarded_host;
spec:
  tls:
    - hosts:
        - pub.ulfurinn.net
      secretName: pub-ingress-tls
  rules:
    - host: pub.ulfurinn.net
      http:
        paths:
          - backend:
              service:
                name: blogpub
                port:
                  number: 80
            path: /
            pathType: Prefix
